apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi-container
        image: kingyuva/weatherapi-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30080